
# An explanation for docker or docker-compose newcomers can be found in the 'docker-compose_documents.yml' file
# Please also use the official docker documentation as a reference:
# https://docs.docker.com/    and    https://docs.docker.com/compose/

# Instructions for necessary settings during setup when using docker-compose deployment can be found here:
# TBD

version: '3'
services:
  srv:
    image: "testrail/apache:${TESTRAIL_VERSION:-latest}"
    restart: unless-stopped
    networks:
      - testrail
    ports:
      - "${HTTP_PORT:-8000}:80"
    volumes:
      - 'testrail_config:/var/www/testrail/config/'
      - 'testrail_opt:/opt/testrail'

networks:
  testrail:
    driver: bridge

volumes:
  testrail_opt:
    driver: local
    driver_opts:
      type: none
      device: "$PWD/${OPT_PATH:-_opt}"
      o: bind

  testrail_config:
    driver: local
    driver_opts:
      type: none
      device: "$PWD/${CONFIG_PATH:-_config}"
      o: bind